name: CI test before any PR merge to main

on: 
  pull_request: # left blank to apply to ALL PRs
  push:
      branches: [main]

jobs:
  check-PR-before-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-python@v7.0.0
        with: 
          python-version: '3.11'

      - name: check if python version comes out as expected
        run: python --version