name: CI test before any PR merge to main

on: 
  pull_request: # left blank to apply to ALL PRs
  push:
      branches: [main]

jobs:
  check-PR-before-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with: 
          python-version: '3.11'

      - name: requirements check
        run: pip install -r requirements.txt

      - name: test importing module
        env: 
          OPENAI_API_KEY: this-is-obviously-not-a-real-API-key-1234567890
        run: python -c "import app.bot_core"
        # test with the most evn dependent module